<center>    
    <h1 id='linear-algebra-notebook-3' style='color:#7159c1; font-size:350%'>Vector Transformations</h1>
    <i style='font-size:125%'>Basics of Vectors</i>
</center>

> **Topics**

```
- 📏 Stretch
- 📏 Squish
- 🪙 Flip
- 🐚 Shear
- ⭕ Rotation
- 🌌 Null
- 🪞 Image
- 🪟 Visualization
```

In [4]:
# ---- Imports ----
import numpy as np
from IPython.display import HTML

# ---- Constants ----
VECTOR = (np.array([2, 1]))
VIDEOS_WIDTH = (600)
VIDEOS_PATH = ('./videos')

# ---- Functions ----
def generateVideoEmbed(path, width):
    """
    Generates a string containing a centered video tag with a specific width and video source.

    - Input:
        / path: string;
        / width: float.

    - Output:
        / video_tag: string.
    """
    video_tag = f'<center><video width="{width}" autoplay controls loop><source src="{path}" type="video/mp4" />Your browser does not support the video tag 😢</video></center>'
    return video_tag

<h1 id='0-stretch' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>📏 | Stretch</h1>

`Stretch` is a transformation where the x-axis and y-axis values of a vector are stretched through a matrix multiplication. For instance, consider a vector $\vec{v}$ being stretched twice in both axis:

$$
\begin{array}
    \vec{v} = \begin{bmatrix} 2, \ 1 \end{bmatrix}
    \quad
    \text{strecth matrix} = \begin{bmatrix} 2, \ 0 \\ 0, \ 2 \end{bmatrix} \\
    \big\downarrow \\
    \vec{v} \cdot \text{stretch matrix} = \begin{bmatrix} 4, \ 2 \end{bmatrix}
\end{array}
$$

In [5]:
# ----- Stretch ----
stretch_matrix = np.array([[2, 0], [0, 2]])
VECTOR @ stretch_matrix

array([4, 2])

<h1 id='1-squish' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>📏 | Squish</h1>

`Squish` is a transformation where the x-axis and y-axis values of a vector are squished through a matrix multiplication. For instance, consider a vector $\vec{v}$ being squished by half in both axis:

$$
\begin{array}
    \vec{v} = \begin{bmatrix} 2, \ 1 \end{bmatrix}
    \quad
    \text{squish matrix} = \begin{bmatrix} 0.50, \ 0 \\ 0, \ 0.50 \end{bmatrix} \\
    \big\downarrow \\
    \vec{v} \cdot \text{squish matrix} = \begin{bmatrix} 1, \ 0.50 \end{bmatrix}
\end{array}
$$

In [6]:
# ---- Squish ----
squish_matrix = np.array([[0.50, 0], [0, 0.50]])
VECTOR @ squish_matrix

array([1. , 0.5])

<h1 id='2-flip' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>🪙 | Flip</h1>

`Flip` is a transformation where the x-axis and y-axis values of a vector are inversed through a matrix multiplication. For instance, consider a vector $\vec{v}$ being flipped in both axis:

$$
\begin{array}
    \vec{v} = \begin{bmatrix} 2, \ 1 \end{bmatrix}
    \quad
    \text{flip matrix} = \begin{bmatrix} -1, \ 0 \\ 0, \ -1 \end{bmatrix} \\
    \big\downarrow \\
    \vec{v} \cdot \text{flip matrix} = \begin{bmatrix} -2, \ -1 \end{bmatrix}
\end{array}
$$

In [7]:
# ---- Flip ----
flip_matrix = np.array([[-1, 0], [0, -1]])
VECTOR @ flip_matrix

array([-2, -1])

<h1 id='3-shear' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>🐚 | Shear</h1>

`Shear` is a transformation where the x-axis and y-axis values of a vector are tilted through a matrix multiplication. It's easier to be visualized in parallelograms rather than vectors, because we can notice the parallelogram being tilted to the either left/right or up/down. For instance, consider a vector $\vec{v}$ being tilted in both axis:

$$
\begin{array}
    \vec{v} = \begin{bmatrix} 2, \ 1 \end{bmatrix}
    \quad
    \text{shear matrix} = \begin{bmatrix} 1, \ 1 \\ 1, \ 1 \end{bmatrix} \\
    \big\downarrow \\
    \vec{v} \cdot \text{shear matrix} = \begin{bmatrix} 3, \ 3 \end{bmatrix}
\end{array}
$$

In [8]:
# ---- Shear ----
shear_matrix = np.array([[1, 1], [1, 1]])
VECTOR @ shear_matrix

array([3, 3])

<h1 id='4-rotation' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>⭕ | Rotation</h1>

`Rotation` is a transformation where the vector is rotated by an angle `theta (θ)`. For instance, consider a vector $\vec{v}$ being rotated in 45º:

$$
\begin{array}
    \vec{v} = \begin{bmatrix} 2, \ 1 \end{bmatrix}
    \quad
    \text{rotation matrix} = \begin{bmatrix} 0.71, \ -0.71 \\ 0.71, \ 0.71 \end{bmatrix} \\
    \big\downarrow \\
    \vec{v} \cdot \text{rotation matrix} = \begin{bmatrix} 2.1213, \ -0.7071 \end{bmatrix}
\end{array}
$$

In [10]:
# ---- Rotation ----
theta = np.radians(45) # 45º in radians
rotation_matrix = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
VECTOR @ rotation_matrix

array([ 2.12132034, -0.70710678])

<h1 id='5-null' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>🌌 | Null</h1>

`Null` is a transformation where the vector is reduced to the origin, getting both x-axis and y-axis values nullified to zero. For instance, consider a vector $\vec{v}$ being nullified:

$$
\begin{array}
    \vec{v} = \begin{bmatrix} 2, \ 1 \end{bmatrix}
    \quad
    \text{null matrix} = \begin{bmatrix} 0, \ 0 \\ 0, \ 0 \end{bmatrix} \\
    \big\downarrow \\
    \vec{v} \cdot \text{null matrix} = \begin{bmatrix} 0, \ 0 \end{bmatrix}
\end{array}
$$

In [11]:
# ---- Null ----
null_matrix = np.array([[0, 0], [0, 0]])
VECTOR @ null_matrix

array([0, 0])

<h1 id='6-image' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>🪞 | Image</h1>

`Image` is a transformation where the vector is kept as-is after being multiplied by an Image Matrix, that is, a diagonal matrix with ones as the diagonal values.

$$
\begin{array}
    \vec{v} = \begin{bmatrix} 2, \ 1 \end{bmatrix}
    \quad
    \text{image matrix} = \begin{bmatrix} 1, \ 0 \\ 0, \ 1 \end{bmatrix} \\
    \big\downarrow \\
    \vec{v} \cdot \text{image matrix} = \begin{bmatrix} 2, \ 1 \end{bmatrix}
\end{array}
$$

In [12]:
# ---- Image ----
image_matrix = np.array([[1, 0], [0, 1]])
VECTOR @ image_matrix

array([2, 1])

<h1 id='7-visualization' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>🪟 | Visualization</h1>

Now, let's see a visualization of each transformation!!

In [13]:
# ---- Visualization ----
HTML(generateVideoEmbed(f'{VIDEOS_PATH}/12-VectorTransformations.mp4', VIDEOS_WIDTH))

---

<h1 id='reach-me' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>📫 | Reach Me</h1>

> **Email** - [csfelix08@gmail.com](mailto:csfelix08@gmail.com?)

> **Linkedin** - [linkedin.com/in/csfelix/](https://www.linkedin.com/in/csfelix/)

> **GitHub:** - [CSFelix](https://github.com/CSFelix)

> **Kaggle** - [DSFelix](https://www.kaggle.com/dsfelix)

> **Portfolio** - [CSFelix.io](https://csfelix.github.io/).